name: Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Install FTP deployment tool
        run: sudo apt-get install lftp
 
      - name: Verificar estrutura do projeto após build
        run: ls -lR
        
      - name: Deploy via FTP  # 🔹 Removido o hífen extra e incluído no bloco steps
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          lftp -e "
          set ssl:verify-certificate no;
          open -u $FTP_USER,$FTP_PASS $FTP_HOST;
          mirror -R ./dist /public_html/app;
          bye"
