- name: Deploy via FTP
  env:
    FTP_HOST: ${{ secrets.FTP_HOST }}
    FTP_USER: ${{ secrets.FTP_USER }}
    FTP_PASS: ${{ secrets.FTP_PASS }}
  run: |
    lftp -c "
    open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST;
    mirror -R ./dist /public_html;
    quit;
    "
